#
# Converse Configuration File
#

# URL where players should appeal their bans
banurl: https://novelmc.net/appeal

# What mode is the server in?
mode: default

# What commands should be blocked when a player is muted?
muted_commands:
  - msg
  - reply
  - tell
  - me
  - mail

# Permissions Configuration
permissions:
  # What is the OP group name?
  op: default

  # What is the Mod group name?
  mod: mod

  # What is the Senior Mod group name?
  senior_mod: seniormod

  # What is the Developer group name?
  developer: developer

  # What is the Executive group name?
  executive: executive

  # What is the Architect group name?
  architect: architect
